http:
    middlewares:
        secureHeaders:
            headers:
                sslRedirect: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
        customHeaders:
            headers:
                customResponseHeaders:
                    Access-Control-Allow-Origin: "https://cms.randomphp.com,https://frandine.randomphp.com,https://api.randomphp.com"
                    Access-Control-Max-Age: "100"
                    Access-Control-Allow-Credentials: "true"
                    Access-Control-Allow-Methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD,CONNECT,TRACE"
                    Access-Control-Allow-Headers: "*"
                    X-Powered-By: "MMSM"
                    Server: "Custom"
        user-auth:
            basicAuth:
                users:
                    - "sicet7:$apr1$Q38fy2jN$olqsiWvwLd6fRI631yECY0"
                    - "nin_leviathan:$apr1$f3uA4oTI$Bam6stj2wbwXMoSDDxfLR1"
                    - "mmsm:$apr1$.ZSM5WRN$qYFsRj3CwTYYX96d5ZvGY1"
tls:
    options:
        default:
            minVersion: VersionTLS12