http:
    middlewares:
        secureHeaders:
            headers:
                sslRedirect: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
        corsHeaders:
            headers:
                accessControlAllowCredentials: true
                accessControlAllowHeaders: "*"
                accessControlAllowMethods:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE
                    - OPTIONS
                    - HEAD
                    - CONNECT
                    - TRACE
                accessControlAllowOriginList:
                    - https://*.randomphp.com
                    - https://randomphp.com
                accessControlMaxAge: 100
                addVaryHeader: true
        user-auth:
            basicAuth:
                users:
                    - "sicet7:$apr1$Q38fy2jN$olqsiWvwLd6fRI631yECY0"
                    - "nin_leviathan:$apr1$f3uA4oTI$Bam6stj2wbwXMoSDDxfLR1"
                    - "mmsm:$apr1$.ZSM5WRN$qYFsRj3CwTYYX96d5ZvGY1"
tls:
    options:
        default:
            minVersion: VersionTLS12