http:
    middlewares:
        secureHeaders:
            headers:
                sslRedirect: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000

        user-auth:
            basicAuth:
                users:
                    - "sicet7:$apr1$Q38fy2jN$olqsiWvwLd6fRI631yECY0"
                    - "nin_leviathan:$apr1$f3uA4oTI$Bam6stj2wbwXMoSDDxfLR1"

tls:
    options:
        default:
            minVersion: VersionTLS12