api:
    dashboard: true

entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure

    websecure:
        address: :443
        http:
            middlewares:
                - secureHeaders@file
                - customHeaders@file
            tls:
                certResolver: letsencrypt-prod

    mc-tcp:
        address: ":25565"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
    file:
        filename: /configurations/dynamic.yml

certificatesResolvers:
    #letsencrypt-staging:
    #    acme:
    #        caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    #        email: 'ssl@sicet7.com'
    #        storage: 'acme-staging.json'
    #        keyType: 'RSA4096'
    #        dnsChallenge:
    #            provider: cloudflare
    #            resolvers:
    #                - "1.1.1.1:53"
    #                - "1.0.0.1:53"
    letsencrypt-prod:
        acme:
            caServer: 'https://acme-v02.api.letsencrypt.org/directory'
            email: 'ssl@sicet7.com'
            storage: 'acme-prod.json'
            keyType: 'RSA4096'
            dnsChallenge:
                provider: cloudflare
                resolvers:
                    - "1.1.1.1:53"
                    - "1.0.0.1:53"